[build]
  publish = "."

[[redirects]]
  from = "/registry"
  to = "/registry.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/archive"
  to = "/archive.html"
  status = 200

[[redirects]]
  from = "/guide"
  to = "/guide.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
